### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [pinguinopedro7/prj-rev-bwfs-dasmoto#4]
Great looking Dasmoto project but please remember to keep your code just as looking good. This is very important as your code base grows as it makes your code legible and easy to navigate through.

Other than that, awesome job!
Grade: Meets expectation.

**Comment by pinguinopedro7** [comment]
Thank you for the feedback! I'll keep in mind that I need to work on the structure of my code for the next project!
